services:
  caddy:
    image: louking/caddy:${APP_VER}
    build:
      dockerfile: Dockerfile
      args:
        - CADDY_UID=${CADDY_UID}
        - CADDY_GID=${CADDY_GID}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/config:/etc/caddy
      - $CADDY_LOG_HOST:/var/log/caddy
      - $CADDY_DATA_HOST:/data
      - $CADDY_CONFIG_HOST:/config
    environment:
      - DEBUG=${DEBUG:-false}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CADDY_UID=${CADDY_UID}
      - CADDY_GID=${CADDY_GID}
    extra_hosts:
      # see https://stackoverflow.com/a/67158212/799921
      - host.docker.internal:host-gateway
    networks:
      - backend-network

networks:
  backend-network:
    name: caddy-backend-network
    external: true

